server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
spring:
  profiles:
    active: secret
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pink_sheep?characterEncoding=UTF-8&serverTimeZone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
logging:
  config: classpath:log4j2.yaml